const token = "eyJhbGciOiJFUzI1NiIsIng1dCI6IkEwMEFDMEE1MzcxMDRBMTM1RDg0NkM4NkFDN0ZERkU1RUE4REIyOTkifQ.eyJvYWEiOiI3Nzc3MCIsImlzcyI6Im9hIiwiYWlkIjoiMTIiLCJ1aWQiOiJPVjZaTDItQVlCMFZ2VzJGekVxejdBPT0iLCJjaWQiOiJPVjZaTDItQVlCMFZ2VzJGekVxejdBPT0iLCJpc2EiOiJUcnVlIiwidGlkIjoiMjAwNSIsInNpZCI6ImQyZGZhOWQwNDI5YjRlYTM4MDNjMmYwZjM3NzIyMzI4IiwiZGdpIjoiODIiLCJleHAiOiIxNDU2Nzc3MDE3In0.35l2VWiOhEOlpQj-ykJInFb3i9HFlXTEoUd0zI15ovUYdDkxaYodtwAWx6A90wkRAQEyEvzEteNETwPZwH81-w";
const baseUrl = 'https://developer.saxobank.com/sim/openapi';

var config = {
    token: token,
    baseUrl: baseUrl
};