
const token = "eyJhbGciOiJFUzI1NiIsIng1dCI6IkEwMEFDMEE1MzcxMDRBMTM1RDg0NkM4NkFDN0ZERkU1RUE4REIyOTkifQ.eyJvYWEiOiI3Nzc3MCIsImlzcyI6Im9hIiwiYWlkIjoiMTIiLCJ1aWQiOiI3YUJRTzgtT0tjSWNjVEY4YVBldGRRPT0iLCJjaWQiOiJVZG1JdTVOVjBTbTI5TVJyZW5acUVnPT0iLCJpc2EiOiJUcnVlIiwidGlkIjoiMjAwNSIsInNpZCI6IjZjY2QwNmM4YjA2ZDQ0NDRiOWVkMDEyMmNhMWI2MWY2IiwiZGdpIjoiODIiLCJleHAiOiIxNDU3NDY1NjYyIn0.OUwwkN4OVI_FjyuyiZ2JksuHZ8FXiX8Ke3UoFHyY6NlALjNC9EYPCCTQ7lC5r8MoOdl3o1c6ANOOCNsq4TJXHg";
const baseUrl = 'https://developer.saxobank.com/sim/openapi';
/*
const token = "eyJhbGciOiJFUzI1NiIsIng1dCI6IjU4NjQ4OEIzMjYxNDI5NjcyMjA5QTcyNkNDNzcyQkUzNDU1Q0E1OTMifQ.eyJvYWEiOiI3Nzc3NyIsImlzcyI6Im9hIiwiYWlkIjoiMzMiLCJ1aWQiOiJGclM0WXFqNkJtajJ6Zkc3b1FRRmN3PT0iLCJjaWQiOiJGclM0WXFqNkJtajJ6Zkc3b1FRRmN3PT0iLCJpc2EiOiJUcnVlIiwidGlkIjoiMTAwMCIsInNpZCI6IjQ0YjYwMGQ0YTRhNTQ1MjViMjNlNmI4MGY4ZTg0YjYxIiwiZGdpIjoiODIiLCJleHAiOiIxNDU3MzY1ODQzIn0.16y4wxNy5y-S8rbVsONkl51ZuptvBV5HQ_1wgzQwo-oTMyD-Yc9TTWjI8vApPYrtrvrVEoz2YUPcAnp13WSmFg";
const baseUrl = 'http://red.openapi.sys.dom/openapi';
*/

var config ={
    token:token,
    baseUrl:baseUrl
};
//export { token, baseUrl };

